Atualiza o README.md
okfn-brasil/querido-diario-comunidade pull request #17
Opened 2022-09-25 19:31 UTC by trevineju

Este PR resolve uma das 8 tarefas da issue #https://github.com/okfn-brasil/querido-diario-comunidade/issues/15 em alinhamento ao discutido na discussion, implementando a documentação padronizada para o `README.md` #https://github.com/okfn-brasil/querido-diario-comunidade/discussions/11

2022-09-27 01:00 UTC, lguima commented on README.md
> +Está interessado(a) em contribuir para o repositório? :tada:
No repositório do frontend, eu havia sugerido o seguinte texto, o que acha?

> Agradecemos por considerar contribuir com o Querido Diário! 🎉
> 
> Você encontra como fazê-lo em nosso [Guia de Contribuição](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/.github/CONTRIBUTING.md).

2022-09-27 01:00 UTC, lguima commented on README.md
> +Este projeto é mantido pela Open Knowledge Brasil e possível graças a comunidade técnica, as [Embaixadoras de Inovação Cívica](https://embaixadoras.ok.org.br/), voluntárias, doadoras financeiras, alé
```suggestion
Este projeto é mantido pela Open Knowledge Brasil e possível graças à comunidade técnica, às [Embaixadoras de Inovação Cívica](https://embaixadoras.ok.org.br/), às pessoas voluntárias e doadoras financeiras, além de universidades parceiras, empresas apoiadoras e financiadoras.

Conheça [quem apoia o Querido Diário](https://queridodiario.ok.org.br/apoie#quem-apoia)
```

2022-09-27 01:01 UTC, lguima commented on README.md
> +# Contribua
Seguindo o padrão de substantivos:

```suggestion
# Contribuição
```

2022-09-27 01:02 UTC, lguima commented on README.md
> +# Sumário
Este README é super sucinto, não sei se precisaria de um sumário.

2022-09-27 21:32 UTC, giuliocc requested changes
No geral acho que o padrão tá ótimo!

Poucas sugestões e podemos seguir :)

2022-09-27 21:32 UTC, giuliocc commented on README.md
> +**Português (BR)** | [English (US)](.github/README-en-US.md) | [Español](.github/README-es.md)
Se o arquivo não existir, não precisamos criar o link aqui. Mas podemos deixar issues criadas para as traduções faltantes.

2022-09-27 21:32 UTC, giuliocc commented on README.md
> +# Sumário
Acho que não faz mal. Pelo menos pra manter o padrão. Em repositórios como a toolbox provavelmente seria necessário.

2022-09-27 21:32 UTC, giuliocc commented on README.md
> +# Contribua
Não sei... Na real eu acho que "Como contribuir" faz mais sentido aqui

2022-09-27 21:32 UTC, giuliocc commented on README.md
> +Está interessado(a) em contribuir para o repositório? :tada:
O texto sugerido pelo @lguima tá ótimo!

2022-09-27 21:32 UTC, giuliocc commented on README.md
> +</p>
O padrão de shield de rede social não consegue ser replicado pra qualquer item, né? Acharia melhor manter um padrão pra evitar dar essas quebras. O que acha?

No caso poderia ser seguindo a estética do shield à direita. Mas quando tivermos a logo do serviço disponível colocaríamos.

2022-09-27 21:32 UTC, giuliocc commented on README.md
> +  </a>
Acho que o Discord tá muito escondido. Não acha? Acho que precisaria de um destaque com uma chamada própria convidando as pessoas conversar sobre o projeto, tirar dúvidas, etc.

2022-09-27 21:32 UTC, giuliocc commented on README.md
> +Conheça [quem apoia o Querido Diário](https://queridodiario.ok.org.br/apoie#quem-apoia)
Faltou o ponto hehehe
```suggestion
Conheça [quem apoia o Querido Diário](https://queridodiario.ok.org.br/apoie#quem-apoia).
```

2022-09-27 22:04 UTC, trevineju commented on README.md
> +# Contribua
Vou aderir à do Giulio. Estava pensando em algo menos impessoal e mais "provocativo" para convocação de contribuição (por isso tinha posto no imperativo). Mas a sugestão parece uma boa conciliação

2022-09-27 22:25 UTC, trevineju commented on README.md
> +</p>
Eu não achei todos esse shields no site oficial por não ter todas as redes sociais, busquei com terceiros. Aqui: https://github.com/alexandresanlim/Badges4-README.md-Profile

sim, acaba que não é replicável para qualquer item. Vou tentar criar os outros

2022-09-28 12:34 UTC, trevineju commented on README.md
> +Está interessado(a) em contribuir para o repositório? :tada:
corrigido

2022-09-28 12:35 UTC, trevineju commented on README.md
> +# Sumário
Apesar de concordar com o @lguima, também acho que é questão de manter o padrão.

2022-09-28 12:35 UTC, trevineju commented on README.md
> +**Português (BR)** | [English (US)](.github/README-en-US.md) | [Español](.github/README-es.md)
retirado

2022-09-28 12:36 UTC, trevineju commented on README.md
> +  </a>
Submeti um commit que adiciona um bloco de "suporte" com o texto para o discord e movi o badge do discord para o topo do readme. Veja o que achou.

2022-09-28 16:12 UTC, giuliocc requested changes
Mais uns comentários e um tutorial de como fazer os shields direitinho hehe

2022-09-28 16:12 UTC, giuliocc commented on README.md
> +</p>
Dei uma lida nesse [shields.io](https://shields.io/) e entendi melhor como se usa as badges.

As palavras que aparecerão seguem o formato `https://img.shields.io/badge/<LABEL>-<MESSAGE>-<COLOR>`, onde `LABEL` aparece na esquerda e `MESSAGE` na direita. O `COLOR` é a cor da `MESSAGE`.

Também temos os estilos, o que estamos usando é o `for-the-badge` e podemos manter ele como principal. O `flat-square` também parece legal mas é bem mais discreto e talvez possamos usar quando for o caso.

![image](https://user-images.githubusercontent.com/26327506/192828957-c3e791c2-906d-4386-b9ba-c73f240a3135.png)

Também dá pra configurar outras coisas como a logo que aparece, cor da label, etc. Isso pode ser feito na querystring do shield:

Parâmetro | Descrição
-- | --
?label=healthinesses | Override the default left-hand-side text (URL-Encoding needed for spaces or special characters!)
?logo=appveyor | Insert one of the named logos from (bitcoin, dependabot, gitlab, npm, paypal, serverfault, stackexchange, superuser, telegram, travis) or simple-icons. Simple-icons are referenced using icon slugs which can be found on the simple-icons site or in the slugs.md file in the simple-icons repository.
?logo=data:image/png;base64,… | Insert custom logo image (≥ 14px high). There is a limit on the total size of request headers we can accept (8192 bytes). From a practical perspective, this means the base64-encoded image text is limited to somewhere slightly under 8192 bytes depending on the rest of the request header.
?logoColor=violet | Set the color of the logo (hex, rgb, rgba, hsl, hsla and css named colors supported). Supported for named logos but not for custom logos.
?logoWidth=40 | Set the horizontal space to give to the logo
?link=http://left&link=http://right | Specify what clicking on the left/right of a badge should do. Note that this only works when integrating your badge in an<object> HTML tag, but not an<img> tag or a markup language.
?labelColor=abcdef | Set background of the left part (hex, rgb, rgba, hsl, hsla and css named colors supported). The legacy name "colorA" is also supported.
?color=fedcba | Set background of the right part (hex, rgb, rgba, hsl, hsla and css named colors supported). The legacy name "colorB" is also supported.
?cacheSeconds=3600 | Set the HTTP cache lifetime (rules are applied to infer a default value on a per-badge basis, any values specified below the default will be ignored). The legacy name "maxAge" is also supported.

Tentei colocar uma logo customizada do Catarse e dá pra fazer. Só tem que encontrar uma imagem pequena e de fundo transparente (PNG ou ICO), [converter pra base64](https://onlineimagetools.com/convert-image-to-base64) e colar o resultado no campo `logo`.

Exemplo de como usar uma logo customizada e com `label` + `message`:

![image](https://user-images.githubusercontent.com/26327506/192830829-047b7bbf-3d9c-47f3-a6ce-74b6a1071c68.png)

```suggestion
<p>  
  <a href="https://www.catarse.me/queridodiario-okbr" target="_blank"> 
    <img alt="catarse" src="https://img.shields.io/badge/Catarse-Apoie o projeto-orange?style=for-the-badge&logo=data:image/ico;base64,AAABAAEAEBIAAAEAIAAXAgAAFgAAAIlQTkcNChoKAAAADUlIRFIAAAAQAAAAEggGAAAAUjteagAAAd5JREFUOI2NlLFrU1EUh7/z7mtIQiWh1ae0SKJBxBaxzyUgBUsULOjQoeCm6V9g1cVB8AUXwSFxcRBB+gYRB3Vw0Mk4OAhCsuiiKVFEsBFqwYJJTa5Dk9fXlzTNb7r33PP77jmcyxWtNSJCUBXbmQIKwGngK5BNlZwigNbayzO6nFt60TYDJIA3FdvJBpP6ARI9YoWK7SQHBZR7xGKAMyhgAaj2iF9ePpmL7wpIlZwyYAPF4Jk5+nG+s5adpuBXxXYeAdnOPnL0CWrPt6vWg/VCvxb81SyIanzxblV/ARb7thCUGv5+f9Ncx4iuQHtKAwMSRTcPMLT/QydU3gaw3PSc5abj3dYthcbeeQBRPPUAlpueAZ6vXHr/ezeAqDoS1gwd2Tjvr6AwagoXnp2a3slcuxa5A2yax5uIYtIPODEWEsZDstTL/OtG+CJNrpsHmoSS/5CwBrgHYLZzqvUWyX2mHH74euLTpKo9njBqL/UPNUODWf40z9DycgGc2JVGzl/BUrXeoqHRq0SPpYzV20BJIjoPnCOqTYY17G0BHIovbuQ6JO8lWm56an7EPDtiyl1L1smoZQ4aa8FuyrEMtv8/6HrKN19NzwG3gORx42d+1vy8BsSBYizDW9j+ofwHqM6MbbvUDjEAAAAASUVORK5CYII=" width="100">
  </a>
</p> 
```

2022-09-28 16:12 UTC, giuliocc commented on README.md
> +    <img alt="Facebook Follow" src="https://img.shields.io/badge/Facebook-1877F2?style=for-the-badge&logo=facebook&logoColor=white" width="105">
Essas `width` com valores diferentes não acabam deixando os shields fora de proporção?

2022-09-28 22:13 UTC, trevineju commented on README.md
> +    <img alt="Facebook Follow" src="https://img.shields.io/badge/Facebook-1877F2?style=for-the-badge&logo=facebook&logoColor=white" width="105">
ao contrário, como os shields prontos que havia pego eram de tamanhos diferentes, precisei editar o `width` para tentar aproximar. Mas com novos shields, pode não ser necessário.

2022-09-28 23:04 UTC, trevineju commented on README.md
> +    <img alt="Facebook Follow" src="https://img.shields.io/badge/Facebook-1877F2?style=for-the-badge&logo=facebook&logoColor=white" width="105">
Não foi necessário

2022-10-05 13:44 UTC, trevineju commented
Este PR agora inclui a atualização do CONTRIBUTING.md também 

No caso, as únicas coisas alteradas foram: 
- reordenar a lista de repositórios para dar destaque aos mais mantidos / assistidos 
- entitulei o bloco "onde contribuir" de "ecossistema do Querido Diário" para aderir à terminologia que viemos usando

2022-10-05 17:33 UTC, giuliocc requested changes
Pequenas alterações sugeridas. Tamo terminando! Hehehehe

---

No contributing, comentando aqui pois não posso especificar a linha como não foi modificada:

O texto pode melhorar um pouco:
1. falar que essas regras valem para todos os repositórios e que algumas particularidades poderão ser encontradas no CONTRIBUTING específico do repositório
2. tem uns "em alguma" e "em a" que poderiam ser alterados pra "caso alguma" ou algo do tipo
3. explicar que `issues` seriam específicas de determinado repositório enquanto `discussions` são transversais aos repositórios do projeto
4. por questões de  manutenção, linkar para https://github.com/okfn-brasil/querido-diario-comunidade#suporte poderia ser melhor que linkar pro discord novamente
5. na parte de manutenção, o último tópico poderia ser substituído por:

- Manter o histórico de commits organizado, preferencialmente seguindo o formato a seguir onde toda alteração na base de código tem como base a `main` atualizada e é mesclada com um *merge commit*:

```mermaid
    gitGraph
       commit
       branch feat-1
       checkout feat-1
       commit
       commit
       commit
       checkout main
       merge feat-1
       branch feat-2
       checkout feat-2
       commit
       checkout main
       merge feat-2
```
- Caso um *Pull Request* tenha muitos *commits* e as mensagens não forem claras, pode-se realizar um *squash* nos *commits* antes de mesclar o *Pull Request*

2022-10-05 17:33 UTC, giuliocc commented on .github/CONTRIBUTING.md
>  - [Censo](https://github.com/okfn-brasil/censo-querido-diario)
Acredito que linkar https://queridodiario.ok.org.br/tecnologia#arquitetura seja melhor

Ficamos com um ponto apenas de modificação e ali tem uma explicação mais completa. O que acha?

2022-10-07 17:54 UTC, trevineju commented on .github/CONTRIBUTING.md
>  - [Censo](https://github.com/okfn-brasil/censo-querido-diario)
Acho que como cada repositório aponta para este guia, é bom ter a lista -- para que as pessoas que cheguem apenas por um lado, acabem sabendo do universo todo. 
O link para arquitetura está linkado no README já.

2022-10-09 22:53 UTC, lguima requested changes
@trevineju

2022-10-09 22:53 UTC, lguima commented on README.md
> +Ingresse em nosso [Discord](https://discord.com/invite/mxHGPq8rdY) para trocas sobre os projetos, dúvidas, pedidos de ajuda com contribuição e conversar sobre inovação cívica em geral.
Poderíamos atualizar o link do Discord nos arquivos de suporte também?
- `.github/SUPPORT.md`
- `.github/SUPPORT-en-US.md`

2023-01-18 22:10 UTC, trevineju commented
Voltando a pegar essa issue! 😮

2023-01-18 22:12 UTC, trevineju commented on README.md
> +Ingresse em nosso [Discord](https://discord.com/invite/mxHGPq8rdY) para trocas sobre os projetos, dúvidas, pedidos de ajuda com contribuição e conversar sobre inovação cívica em geral.
vou atualizar o link pro discord em `support.md`, só não farei isso no em ENG pq ainda não estamos focando no segundo idioma. Por uma questão de etapas msm, de fechar o em PTBR e aí passar a corrigir a tradução (tanto é que arquivo em ENG está com todo o texto ultrapassado já, praticamente)

2023-01-18 22:17 UTC, trevineju commented on .github/CONTRIBUTING.md
>  - [Censo](https://github.com/okfn-brasil/censo-querido-diario)
Olhando agora do futuro, meu comentário tá mal escrito, mas mantenho que acho melhor ter a lista pra manter a pessoa que já está no GitHub no próprio GitHub.

2023-01-18 22:55 UTC, trevineju commented
Pronto para revisão. Aguardo revisão para dar rebase no histórico.

2023-01-18 23:56 UTC, lguima requested changes
@trevineju

2023-01-18 23:56 UTC, lguima commented on README.md
> +Ingresse em nosso [Discord](SUPPORT.md) para trocas sobre os projetos, dúvidas, pedidos de ajuda com contribuição e conversar sobre inovação cívica em geral.
O link é para o arquivo de suporte ou para o Discord?

```suggestion
Ingresse em nosso [Discord](https://go.ok.org.br/discord) para trocas sobre os projetos, dúvidas, pedidos de ajuda com contribuição e conversar sobre inovação cívica em geral.
```

```suggestion
Ingresse em nosso [Discord](.github/SUPPORT.md) para trocas sobre os projetos, dúvidas, pedidos de ajuda com contribuição e conversar sobre inovação cívica em geral.
```

2023-01-19 00:05 UTC, trevineju commented on README.md
> +Ingresse em nosso [Discord](SUPPORT.md) para trocas sobre os projetos, dúvidas, pedidos de ajuda com contribuição e conversar sobre inovação cívica em geral.
Fui commitar a alteração que adiciona o `.github/` e aceitei as duas modificações. Só que a primeira está certo a referencia ser para o `support.md`. 
Sei que fica um pouco feio e meio encapsulado (a pessoa teria que dar um clique extra: readme -> support -> discord), mas a intenção é nos poupar de dar manutenção. Se por algum motivo o canal mudar (abandonamos o discord) ou o link para o discord mudar, não precisamos mudar o link em vários locais, apenas em `support` já que tudo estará apontando pra ele.

2023-01-19 00:06 UTC, trevineju commented on README.md
> +Ingresse em nosso [Discord](SUPPORT.md) para trocas sobre os projetos, dúvidas, pedidos de ajuda com contribuição e conversar sobre inovação cívica em geral.
Vou fazer um commit que desfaz a correção que aceitei por acidente. E já vou melhorar esse texto ali tb, deixar mais genérico.

2023-01-19 00:07 UTC, lguima commented on README.md
> +Ingresse em nosso [Discord](https://discord.com/invite/mxHGPq8rdY) para trocas sobre os projetos, dúvidas, pedidos de ajuda com contribuição e conversar sobre inovação cívica em geral.
@trevineju acho que ficou confusa minha sugestão, me desculpa.

Eu não tinha sugerido trocar o link do Discord do README pelo do arquivo de suporte.

Sugeri trocar o link do Discord NO arquivo de suporte hehe

- [`.github/SUPPORT.md`](https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/.github/SUPPORT.md)

Lá o link do Discord está desatualizado.

2023-01-19 00:09 UTC, trevineju commented on README.md
> +Ingresse em nosso [Discord](https://discord.com/invite/mxHGPq8rdY) para trocas sobre os projetos, dúvidas, pedidos de ajuda com contribuição e conversar sobre inovação cívica em geral.
boa, tb reparei isso mais cedo e já está feito no commit: https://github.com/okfn-brasil/querido-diario-comunidade/pull/17/commits/b2bcb2905cf7677a1a532e767ee25a1b6492b840

2023-01-19 00:12 UTC, lguima approved these changes
LGTM 🚀

2023-01-20 23:09 UTC, giuliocc requested changes
Deixei alguns comentários mas acho que tá 99% pronto! @rasrbk teria alguma coisa a acrescentar?

2023-01-20 23:09 UTC, giuliocc commented on .github/CONTRIBUTING.md
> +Na aba **Issues** do repositório escolhido ficam as tarefas pendentes. Veja se uma te interessa.
```suggestion
Na aba **Issues** do repositório escolhido ficam as tarefas ou problemas específicos daquele repositório. Veja se uma te interessa.
```

2023-01-20 23:09 UTC, giuliocc commented on .github/CONTRIBUTING.md
> +Caso tenha uma ideia ou sugestão para os rumos do repositório em específico ou do projeto como um todo, crie uma **Discussion** (discussão).
```suggestion
Caso tenha uma ideia ou sugestão para os rumos do projeto, crie uma **Discussion** (discussão).
```
Ideia ou sugestão para um repositório em específico entra em issues também. Se for compartimentalizado o suficiente é melhor ficar mais próximo do objeto da discussão.

2023-01-20 23:09 UTC, giuliocc commented on .github/CONTRIBUTING.md
> +Ingresse na [comunidade](SUPPORT.md). Lá você poderá tirar dúvidas mais rápidas, interagir com as pessoas mantenedoras, perguntar como poderia ajudar e ainda conversar com outras pessoas que também c
Assim como no README acho que esse link intermediário poderia ir direto para o discord.

2023-01-23 17:38 UTC, trevineju commented on README.md
> +Ingresse em nosso [canal de comunidade](.github/SUPPORT.md) para trocas sobre os projetos, dúvidas, pedidos de ajuda com contribuição e conversar sobre inovação cívica em geral.
alterado

2023-01-23 17:38 UTC, trevineju commented on .github/CONTRIBUTING.md
> +Ingresse na [comunidade](SUPPORT.md). Lá você poderá tirar dúvidas mais rápidas, interagir com as pessoas mantenedoras, perguntar como poderia ajudar e ainda conversar com outras pessoas que também c
também alterado

2023-02-03 15:24 UTC, merged