tradução da página de arquitetura para o inglês
okfn-brasil/querido-diario-comunidade pull request #73
Opened 2023-10-07 14:45 UTC by MoisesMsa

Close #66

2023-10-10 19:26 UTC, ogecece requested changes
Obrigado pela contribuição @MoisesMsa ! 

Só precisamos corrigir alguns problemas de hiperlink que não estão conectando e um parágrafo que ficou em português :)

2023-10-10 19:26 UTC, ogecece commented on docs/architecture.rst
> +`postgresql`+ for interacting with the data extracted from the spiders, and a lot of pure Python.
```suggestion
`postgresql`_ for interacting with the data extracted from the spiders, and a lot of pure Python.
```

2023-10-10 19:26 UTC, ogecece commented on docs/architecture.rst
> +.. _Dear Diary Census: https://censo.ok.org.br/
```suggestion
.. _Censo Querido Diário: https://censo.ok.org.br/
```

2023-10-10 19:26 UTC, ogecece commented on docs/architecture.rst
> +.. _Dear Diary Toolbox: https://github.com/okfn-brasil/querido-diario-toolbox
```suggestion
.. _Querido Diário Toolbox: https://github.com/okfn-brasil/querido-diario-toolbox
```

2023-10-10 19:26 UTC, ogecece commented on docs/architecture.rst
> +também é aberto.
O parágrafo ficou sobrando hehe

2023-10-11 16:24 UTC, trevineju approved these changes
Fiz alguns ajustes só. Obrigada pela contribuição, @MoisesMsa! <img src="https://media0.giphy.com/media/MldYzOabP5S8pkbEaK/giphy.gif"/>

2023-10-11 16:25 UTC, merged

2023-10-12 03:45 UTC, MoisesMsa commented
> Fiz alguns ajustes só. Obrigada pela contribuição, @MoisesMsa! ![](https://camo.githubusercontent.com/e56a0149b953e6fd1b4b29b230308f11187f9433740f169c26750d848af60fa7/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f4d6c64597a4f616250355338706b6245614b2f67697068792e676966) [ ![68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f4d6c64597a4f616250355338706b6245614b2f67697068792e676966](https://camo.githubusercontent.com/e56a0149b953e6fd1b4b29b230308f11187f9433740f169c26750d848af60fa7/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f4d6c64597a4f616250355338706b6245614b2f67697068792e676966) ](https://camo.githubusercontent.com/e56a0149b953e6fd1b4b29b230308f11187f9433740f169c26750d848af60fa7/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f4d6c64597a4f616250355338706b6245614b2f67697068792e676966) [ ](https://camo.githubusercontent.com/e56a0149b953e6fd1b4b29b230308f11187f9433740f169c26750d848af60fa7/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f4d6c64597a4f616250355338706b6245614b2f67697068792e676966)

Valeu, estava esperando um tempinho pra ajustar o/