Atualizar versão em inglês do README - v1
okfn-brasil/querido-diario-comunidade pull request #75
Opened 2023-10-09 02:31 UTC by jufajardini

Closes #16

Fiz também um commit extra quebrando as linhas do README em cerca de 90 caracteres, aí se não for do interesse do projeto, fica fácil descartar.

2023-10-10 19:55 UTC, ogecece requested changes
Tá ótimo! Só achei uma observação:

2023-10-10 19:55 UTC, ogecece commented on .github/README-en-US.md
> +You can find out how to do that in our [Contribution Guide](CONTRIBUTING-en-US.md).
Opa, ficou faltando o escudo do Catarse

2023-10-10 23:20 UTC, jufajardini commented on .github/README-en-US.md
> +You can find out how to do that in our [Contribution Guide](CONTRIBUTING-en-US.md).
E a vergonha de deixar escapar algo assim? XD
Vou corrigir 🙇🏽

2023-10-10 23:27 UTC, jufajardini commented on .github/README-en-US.md
> +You can find out how to do that in our [Contribution Guide](CONTRIBUTING-en-US.md).
Feito!

2023-10-11 13:50 UTC, ogecece commented on .github/README-en-US.md
> +You can find out how to do that in our [Contribution Guide](CONTRIBUTING-en-US.md).
Hahahahaha nada pô, acontece

2023-10-11 13:53 UTC, ogecece approved these changes
Tá ótimo @jufajardini ! 

![_](https://media.tenor.com/3khW5vIEG30AAAAC/tocaae-enois.gif)

2023-10-11 13:53 UTC, merged