Atualiza textos na documentação oficial do projeto
okfn-brasil/querido-diario-comunidade pull request #92
Opened 2023-11-27 20:31 UTC by trevineju

2024-01-09 19:21 UTC, trevineju commented on docs/pt_BR/source/index.rst
> +O projeto Querido Diário (QD) propõe classificar, contextualizar e expandir a
classificar?

2024-01-09 19:24 UTC, trevineju commented on docs/pt_BR/source/utilizando/buscador.rst
> +Interface de busca
Acho que "buscador" é mais inclusivo pras pessoas mesmo

2024-02-06 13:41 UTC, trevineju commented
PR está pronto. A preview está em: https://querido-diario--92.org.readthedocs.build/pt-br/92/index.html

Só fiquei com a impressão que o texto de apresentação no `index` poderia ser mais impressionante, por ser a página inicial, e deixar pro `conheca` uma redação mais formal. Mas também não tive ideias boas de escrita.

2024-02-09 12:15 UTC, ogecece requested changes
Sugeri poucas mudanças estruturais. Pra mim o guia de contribuição tá coerente para contextualizar pessoas mais iniciantes e objetivo o suficiente pra não cansar demais quem já entende. Não acho que precisamos levar material pra parte do "entendendo o projeto".

Ficou excelente!

2024-02-09 21:52 UTC, trevineju commented on docs/pt_BR/source/entendendo/conheca.rst
> +O `Tecnologias na Educação`_ é uma ferramenta capaz de identificar atos relacionados
Aqui tinha um problema com o uso dos dois pontos no meio da referência (precisaria escapá-lo). Vou tentar rever isso.

2024-02-16 14:59 UTC, trevineju commented on docs/pt_BR/source/entendendo/conheca.rst
> +Projetos Relacionados
Padronizei o estilo da seguinte forma: O título da página começa com maiúsculas em todas as palavras, e os subtítulos das seções, apenas na primeira palavra. Exemplo: Guia de Contribuição e Raspadores está com maiúsculas, as seções, não. 
![image](https://github.com/okfn-brasil/querido-diario-comunidade/assets/44185775/3aa706d0-353e-4de3-8b60-7025d6ad3b94)

2024-02-16 14:59 UTC, trevineju commented on docs/pt_BR/source/entendendo/conheca.rst
> +Projetos Relacionados
Projetos Relacionados ser página própria com prints dos projetos: feito!

2024-02-16 15:01 UTC, trevineju commented on docs/pt_BR/source/entendendo/arquitetura.rst
> +situações das quais o Querido Diário parte e onde ele se propõe a chegar, o que oferece.
Desafios e Pilares movido para página de Conheça

2024-02-16 15:07 UTC, trevineju commented on docs/pt_BR/source/entendendo/arquitetura.rst
> +    :alt: [TODO]
Diagrama ajustado. Só não liguei ao ponto, pq achei que parecia induzir que transformar um arquivo fechado em aberto era algo que acontecia apenas naquele ponto. Daí referenciei a coluna.

2024-02-16 15:10 UTC, trevineju commented on docs/pt_BR/source/contribuindo/raspadores.rst
> +   * - :attr:`file_urls`
Mudado!

2024-02-16 15:11 UTC, trevineju commented on docs/pt_BR/source/contribuindo/raspadores.rst
> +    :alt: [TODO]
Logo acima, no texto, estava falando que é o Scrapy que de fato executa a ação de baixar o diário, por isso destaquei o downloader na imagem.

2024-02-16 15:14 UTC, trevineju commented on docs/pt_BR/source/contribuindo/raspadores.rst
> +     - `parse()`_
Feito. Porém não gostei como ficou, acho que poluiu demais o campo. Nesse caso, acho que a tabela ficaria melhor mesmo, visto que os itens dela referenciava os campos.

2024-02-16 15:17 UTC, trevineju commented on docs/pt_BR/source/contribuindo/raspadores.rst
> +- ``-s LOG_FILE=nome_arquivo.txt`` salva as mensagens de log em arquivo de texto
troquei o `.log`, porém deixei o `-s` para manter o padrão (-a, -o, -s, etc)

2024-02-16 19:14 UTC, trevineju commented on docs/pt_BR/source/contribuindo/raspadores.rst
> +de campos de pesquisa ou cliques em botões.
Reescrevi quase todo o bloco 6 no commit https://github.com/okfn-brasil/querido-diario-comunidade/pull/92/commits/f5e1d7be2edbf08c0637455cc0c29fe7bee307f5, usando o texto do seu comentário

2024-02-16 19:16 UTC, trevineju commented on docs/pt_BR/source/contribuindo/raspadores.rst
> +Independentemente do caminho, o fluxo de execução sempre desemboca em :meth:`parse()`.
Tirei esse "Independentemente do caminho" e criei uma nova subseção para endereçar essa possibilidade. Ver: https://github.com/okfn-brasil/querido-diario-comunidade/pull/92/commits/f5e1d7be2edbf08c0637455cc0c29fe7bee307f5

2024-02-16 19:18 UTC, trevineju commented on docs/pt_BR/source/contribuindo/raspadores.rst
> +    :alt: [TODO]
Reescrevi a seção e mudei a imagem tb. Deixei só o caminho padrão ilustrado, sem ficar ramificando as possibilidades. Tb separei elemento de scrapy engine do scrapy downloader

2024-02-19 18:43 UTC, ogecece commented on docs/pt_BR/source/entendendo/conheca.rst
> +O `Tecnologias na Educação`_ é uma ferramenta capaz de identificar atos relacionados
Subi uma correção do nome

2024-02-20 16:11 UTC, ogecece requested changes
Subi umas modificações na página de arquitetura (fico aguardando apenas a nova imagem do fluxo das etapas) e também no embed do vídeo no uso da API. Vê aí o que acha.

Fora isso, acho que só tenho um questão a mais pra pedir. Tá 100/100

2024-02-20 16:11 UTC, ogecece commented on docs/pt_BR/source/contribuindo/raspadores.rst
> +     - `parse()`_
achei que ficou ok

2024-02-20 16:11 UTC, ogecece commented on docs/pt_BR/source/contribuindo/raspadores.rst
> +de campos de pesquisa ou cliques em botões.
ficou ótimo!

2024-02-20 17:40 UTC, trevineju commented on docs/pt_BR/source/entendendo/projetos-relacionados.rst
> +.. image:: https://querido-diario-static.nyc3.cdn.digitaloceanspaces.com/documentacao-tecnica/projetos-relacionados/tecnologias-na-educacao.png
feito!

2024-02-21 17:11 UTC, ogecece approved these changes
Tá shou! Só dá uma organizada nos commits e podemos mesclar.

![_](https://c.tenor.com/B8-iSLBttiEAAAAC/tenor.gif)

2024-02-23 22:45 UTC, merged